 version: 2.1
 jobs:
    fmt: 
      docker:  
        - image: hashicorp/terraform:full 
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command
        - run: terraform fmt -check=true 
    init:
      docker: 
        - image: hashicorp/terraform:full 
      steps:
        - run: terraform init   
    plan:
      docker: 
        - image: hashicorp/terraform:full 
      steps:
        - run: terraform plan
    apply:
      docker: 
        - image: hashicorp/terraform:full 
      steps:
        - run: terraform apply -auto-approve
workflows:
  version: 2
  build_and_test:
    jobs:
      - fmt
      - init
      - plan
      - apply

