 version: 2.1
 jobs:
    build:
      docker: 
        - image: hashicorp/terraform:full 
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command
        - run: terraform fmt -check=true 
