version: 2
jobs:
    fmt: 
      docker:  
        - image: hashicorp/terraform:full
      working_directory: ~/circleci-demo-workflows 
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command
        - run: terraform fmt -check=true 
    sleep:
      docker: 
        - image: hashicorp/terraform:full 
      working_directory: ~/circleci-demo-workflows
      steps:
        - run: sleep 60
    init:
      docker: 
        - image: hashicorp/terraform:full 
      working_directory: ~/circleci-demo-workflows
      steps:
        - run: terraform init   
    plan:
      docker: 
        - image: hashicorp/terraform:full 
      working_directory: ~/circleci-demo-workflows
      steps:
        - run: terraform plan
    apply:
      docker: 
        - image: hashicorp/terraform:full 
      working_directory: ~/circleci-demo-workflows
      steps:
        - run: terraform apply -auto-approve
workflows:
  version: 2
  build_and_test:
    jobs:
      - fmt
      - sleep
      - init:
          requires:
            - fmt
      - plan:
          requires:
            - init
      - apply:
          requires:
            - plan
                

