version: 2
executors:
  terraform:
    docker:
      - image: hashicorp/terraform:full
    working_directory: ~/circleci-demo-workflows 
  helloworld:
    docker:
      - image: ubuntu
    working_directory: ~/circleci-demo-workflows 
jobs:
    fmt: 
      my-executor: terraform  
      steps:
        - attach_workspace:
            at: ~/circleci-demo-workflows
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command
        - run: terraform fmt -check=true 
        - run: pwd
        - run: ls -alF
        - persist_to_workspace:
            root: /root/circleci-demo-workflows
            paths: '*'
    sleep:
      my-executor: helloworld
      steps:
        - run: sleep 60
    init:
      my-executor: terraform  
      working_directory: ~/circleci-demo-workflows
      steps:
        - attach_workspace:
            at: ~/circleci-demo-workflows
        - run: pwd
        - run: ls -alF
        - run: terraform init   
        - run: ls -alF
        - persist_to_workspace:
            root: /root/circleci-demo-workflows
            paths: '*'
    plan:
      my-executor: terraform  
      working_directory: ~/circleci-demo-workflows
      steps:
        - attach_workspace:
            at: ~/circleci-demo-workflows
        - run: terraform plan
        - persist_to_workspace:
            root: /root/circleci-demo-workflows
            paths: '*'
    apply:
      my-executor: terraform  
      working_directory: ~/circleci-demo-workflows
      steps:
        - attach_workspace:
            at: ~/circleci-demo-workflows
        - run: terraform apply -auto-approve
workflows:
  version: 2
  build_and_test:
    jobs:
      - fmt
      - sleep:
          requires:
            - fmt
      - init:
          requires:
            - fmt
      - plan:
          requires:
            - init
      - apply:
          requires:
            - plan
            - sleep
                

