version: 2
jobs:
    fmt: 
      docker:  
        - image: hashicorp/terraform:full
      working_directory: ~/circleci-demo-workflows 
      steps:
        - attach_workspace:
            at: ~/circleci-demo-workflows
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command
        - run: terraform fmt -check=true 
        - run: pwd
        - run: ls -alF
        - persist_to_workspace:
            root: /root/circleci-demo-workflows
            paths: *
    sleep:
      docker: 
        - image: hashicorp/terraform:full 
      working_directory: ~/circleci-demo-workflows
      steps:
        - run: sleep 60
    init:
      docker: 
        - image: hashicorp/terraform:full 
      working_directory: ~/circleci-demo-workflows
      steps:
        - attach_workspace:
            at: ~/circleci-demo-workflows
        - run: pwd
        - run: ls -alF
        - run: terraform init   
        - run: ls -alF
    plan:
      docker: 
        - image: hashicorp/terraform:full 
      working_directory: ~/circleci-demo-workflows
      steps:
        - attach_workspace:
            at: ~/circleci-demo-workflows
        - run: terraform plan
    apply:
      docker: 
        - image: hashicorp/terraform:full 
      working_directory: ~/circleci-demo-workflows
      steps:
        - attach_workspace:
            at: ~/circleci-demo-workflows
        - run: terraform apply -auto-approve
workflows:
  version: 2
  build_and_test:
    jobs:
      - fmt
      - sleep:
          requires:
            - fmt
      - init:
          requires:
            - fmt
      - plan:
          requires:
            - init
      - apply:
          requires:
            - plan
            - sleep
                

